import { Inder } from "next/font/google";
import "./globals.css";
import { Metadata } from "next";

// Importando a fonte Inder (apenas peso regular)
const inder = Inder({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-inder",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inder.variable} antialiased`}>{children}</body>
    </html>
  );
}
